language: rust
rust:
  - stable
script:
  - if [ "$TRAVIS_BRANCH == "master" ]; then cargo build --verbose --release; cargo test --verbose; fi
  - if [ "$TRAVIS_BRANCH != "master" ]; then cargo build --verbose; cargo test --verbose; fi
os:
  - linux
  - osx
  - windows
before_deploy:
  - "if [[ -f target/release/sysinfo ]]; then mv target/release/sysinfo \"target/release/sysinfo-$TRAVIS_TAG-$TRAVIS_OS_NAME\"; fi"
  - "if [[ -f target/release/sysinfo.exe ]]; then mv target/release/sysinfo.exe \"target/release/sysinfo-$TRAVIS_TAG-$TRAVIS_OS_NAME.exe\"; fi"
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file_glob: true
    file:
      - target/release/sysinfo-*
    api_key:
      secure: travis-ci_build_token
