[package]
name = "sysinfo_report"
version = "0.3.0"
authors = ["George Hipp <george.hipp.jr@gmail.com>"]
edition = "2018"

[dependencies]
sysinfo = "0.8.4"
os_info = "1.1.1"
structopt = "0.2.10"
assert_cli = "0.5"
cfg-if = "0.1.9"
